server.port=8080

spring.cloud.gateway.routes[0].id=doctor-service
spring.cloud.gateway.routes[0].uri=lb://doctor-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/doctors/**

spring.cloud.gateway.routes[1].id=appointment-service
spring.cloud.gateway.routes[1].uri=lb://appointment-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/appointments/**
